Repository hmcts/pcq-backend, pull requests merged in 2020-12, with the labels that each got.

#207 PCQ-740: Fixing nightly build and updaing docker script.
  bin/set-pcq-docker-env.sh
  build.gradle
  config/owasp/suppressions.xml
  docker-compose.yml
Labels: ns:pcq, prd:pcq, rel:pcq-backend-pr-207

#208 PCQ-742 Addressing CVE-2020-17527 in PCQ-Backend
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:pcq, prd:pcq, rel:pcq-backend-pr-208

#210 PCQ_744_Added suppression for the low severity CVE
  config/owasp/suppressions.xml
Labels: ns:pcq, prd:pcq, rel:pcq-backend-pr-210

#213 PCQ-745_Fix CVE-2020-28052
  build.gradle
Labels: ns:pcq, prd:pcq, rel:pcq-backend-pr-213

#214 PCQ_745_Fixed a failing integ test
  src/integrationTest/java/uk/gov/hmcts/reform/pcqbackend/controllers/GetPcqRecordWithoutCaseTest.java
Labels: ns:pcq, prd:pcq, rel:pcq-backend-pr-214
