Repository hmcts/pcq-backend, pull requests merged in 2020-03, with the labels that each got.

#5 Updated Chart.yml version field
  Jenkinsfile_CNP
  Jenkinsfile_nightly
  build.gradle
  charts/pcq-backend/Chart.yaml
  src/smokeTest/java/uk/gov/hmcts/reform/pcqbackend/DeleteMe.java
Labels: ns:pcq, rel:pcq-backend-pr-5

#6 Infrastructure configuration
  .gitignore
  infrastructure/aat.tfvars
  infrastructure/main.tf
  infrastructure/variables.tf
Labels: ns:pcq, rel:pcq-backend-pr-6

#7 Infrastructure adjustments
  infrastructure/aat.tfvars
  infrastructure/main.tf
  infrastructure/variables.tf
Labels: ns:pcq, rel:pcq-backend-pr-7

#9 Pcq 54 add smoke tests
  .gitignore
  build.gradle
  config/owasp/suppressions.xml
  src/main/java/uk/gov/hmcts/reform/pcqbackend/security/SecurityConfiguration.java
  src/main/resources/application.properties
  src/smokeTest/java/uk/gov/hmcts/reform/pcqbackend/DeleteMe.java
  src/smokeTest/java/uk/gov/hmcts/reform/pcqbackend/smoke/SmokeTestConfiguration.java
  src/smokeTest/java/uk/gov/hmcts/reform/pcqbackend/smoke/SmokeTests.java
  src/smokeTest/resources/application.properties
Labels: ns:pcq, rel:pcq-backend-pr-9

#16 Updated rest-assured version
  build.gradle
Labels: ns:pcq, rel:pcq-backend-pr-16

#17 pcq-44-Added security zap-api config
  .travis.yml
  Jenkinsfile_nightly
  src/main/java/uk/gov/hmcts/reform/pcqbackend/controllers/PcqAnswersController.java
  src/security.sh
Labels: ns:pcq, rel:pcq-backend-pr-17

#18 pcq-114-pit-testing-configuration
  Jenkinsfile_nightly
  build.gradle
  config/owasp/suppressions.xml
  security.sh
Labels: ns:pcq, rel:pcq-backend-pr-18

#20 PCQ-114-Updated pitest to version 1.4.6
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:pcq, rel:pcq-backend-pr-20

#21 pcq-37-functional-test-config-changes
  .gitignore
  Jenkinsfile_CNP
  Jenkinsfile_nightly
  build.gradle
  config/owasp/suppressions.xml
  functional-ouput/.gitignore
Labels: ns:pcq, rel:pcq-backend-pr-21

#22 pcq-47-added-reporting
  Jenkinsfile_CNP
  build.gradle
Labels: ns:pcq, rel:pcq-backend-pr-22

#36 Pcq 157 add database persistence framework
  .env
  README.md
  build.gradle
  charts/pcq-backend/Chart.yaml
  charts/pcq-backend/values.preview.template.yaml
  charts/pcq-backend/values.yaml
  config/owasp/suppressions.xml
  config/pmd/ruleset.xml
  docker-compose.yml
  docker/database/Dockerfile
  docker/database/init-db.sh
  src/integrationTest/java/uk/gov/hmcts/reform/pcqbackend/config/SwaggerPublisher.java
  src/integrationTest/java/uk/gov/hmcts/reform/pcqbackend/controllers/PcqSubmitAnswersControllerTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/pcqbackend/controllers/TestContainerDbTest.java
  src/integrationTest/resources/JsonSchema/answer_definitions_schema.json
  src/integrationTest/resources/JsonSchema/submitAnswersSchema.json
  src/integrationTest/resources/application.yaml
  src/main/java/uk/gov/hmcts/reform/pcqbackend/Application.java
  src/main/java/uk/gov/hmcts/reform/pcqbackend/config/AppConfig.java
  src/main/java/uk/gov/hmcts/reform/pcqbackend/config/FlywayConfiguration.java
  src/main/java/uk/gov/hmcts/reform/pcqbackend/controllers/PcqAnswersController.java
  src/main/java/uk/gov/hmcts/reform/pcqbackend/domain/ProtectedCharacteristics.java
  src/main/java/uk/gov/hmcts/reform/pcqbackend/exceptions/MigrationScriptException.java
  src/main/java/uk/gov/hmcts/reform/pcqbackend/model/PcqAnswerResponse.java
  src/main/java/uk/gov/hmcts/reform/pcqbackend/model/PcqAnswers.java
  src/main/java/uk/gov/hmcts/reform/pcqbackend/repository/ProtectedCharacteristicsRepository.java
  src/main/java/uk/gov/hmcts/reform/pcqbackend/security/SecurityConfiguration.java
  src/main/java/uk/gov/hmcts/reform/pcqbackend/service/SubmitAnswersService.java
  src/main/java/uk/gov/hmcts/reform/pcqbackend/utils/ConversionUtil.java
  src/main/java/util/FlywayNoOpStrategy.java
  src/main/resources/JsonSchema/answer_definitions_schema.json
  src/main/resources/JsonSchema/submitAnswersSchema.json
  src/main/resources/META-INF/spring.factories
  src/main/resources/application.yaml
  src/main/resources/db/migration/V001__Schema.sql
  src/main/resources/uk/gov/hmcts/reform/pcqbackend/gitcommit/git.properties
  src/main/resources/uk/gov/hmcts/reform/pcqbackend/gitcommit/git.properties.old
  src/test/java/uk/gov/hmcts/reform/pcqbackend/controllers/PcqAnswersControllerTest.java
  src/test/java/uk/gov/hmcts/reform/pcqbackend/service/SubmitAnswersServiceTest.java
  src/test/java/uk/gov/hmcts/reform/pcqbackend/util/FlywayNoOpStrategyTest.java
  src/test/resources/JsonSchema/answer_definitions_schema.json
  src/test/resources/JsonSchema/submitAnswersSchema.json
  src/test/resources/JsonTestFiles/DobSubmitAnswer.json
  src/test/resources/JsonTestFiles/FirstSubmitAnswer.json
  src/test/resources/JsonTestFiles/InvalidJson1.json
  src/test/resources/application.yaml
Labels: ns:pcq, rel:pcq-backend-pr-36

#40 Pcq 162 integration-test-with-updatedschema
  Jenkinsfile_CNP
  docker/database/init-db.sh
  src/integrationTest/resources/JsonSchema/answer_definitions_schema.json
  src/integrationTest/resources/JsonSchema/submitAnswersSchema.json
  src/integrationTest/resources/JsonTestFiles/DobSubmitAnswer.json
  src/integrationTest/resources/JsonTestFiles/FirstSubmitAnswer.json
  src/integrationTest/resources/JsonTestFiles/InvalidJson1.json
  src/integrationTest/resources/JsonTestFiles/InvalidVersion.json
  src/main/java/uk/gov/hmcts/reform/pcqbackend/controllers/PcqAnswersController.java
  src/main/java/uk/gov/hmcts/reform/pcqbackend/domain/ProtectedCharacteristics.java
  src/main/java/uk/gov/hmcts/reform/pcqbackend/model/PcqAnswerRequest.java
  src/main/java/uk/gov/hmcts/reform/pcqbackend/model/PcqAnswerResponse.java
  src/main/java/uk/gov/hmcts/reform/pcqbackend/model/SubmitResponse.java
  src/main/java/uk/gov/hmcts/reform/pcqbackend/repository/ProtectedCharacteristicsRepository.java
  src/main/java/uk/gov/hmcts/reform/pcqbackend/service/SubmitAnswersService.java
  src/main/java/uk/gov/hmcts/reform/pcqbackend/utils/ConversionUtil.java
  src/main/resources/JsonSchema/answer_definitions_schema.json
  src/main/resources/JsonSchema/submitAnswersSchema.json
  src/main/resources/db/migration/V002__Schema.sql
  src/main/resources/uk/gov/hmcts/reform/pcqbackend/gitcommit/git.properties
  src/test/java/uk/gov/hmcts/reform/pcqbackend/controllers/PcqAnswersControllerTest.java
  src/test/java/uk/gov/hmcts/reform/pcqbackend/service/SubmitAnswersServiceTest.java
  src/test/resources/JsonSchema/answer_definitions_schema.json
  src/test/resources/JsonSchema/submitAnswersSchema.json
  src/test/resources/JsonTestFiles/DobSubmitAnswer.json
  src/test/resources/JsonTestFiles/FirstSubmitAnswer.json
  src/test/resources/JsonTestFiles/InvalidJson1.json
  src/test/resources/JsonTestFiles/InvalidVersion.json
Labels: ns:pcq, rel:pcq-backend-pr-40

#43 Schema changes for case id, service id and actor
  src/integrationTest/resources/JsonSchema/submitAnswersSchema.json
  src/integrationTest/resources/JsonTestFiles/DobSubmitAnswer.json
  src/integrationTest/resources/JsonTestFiles/FirstSubmitAnswer.json
  src/integrationTest/resources/JsonTestFiles/InvalidJson1.json
  src/integrationTest/resources/JsonTestFiles/InvalidVersion.json
  src/main/java/uk/gov/hmcts/reform/pcqbackend/domain/ProtectedCharacteristics.java
  src/main/java/uk/gov/hmcts/reform/pcqbackend/model/PcqAnswerRequest.java
  src/main/java/uk/gov/hmcts/reform/pcqbackend/model/PcqAnswerResponse.java
  src/main/resources/JsonSchema/submitAnswersSchema.json
  src/main/resources/db/migration/V003__Schema.sql
  src/main/resources/uk/gov/hmcts/reform/pcqbackend/gitcommit/git.properties
  src/test/resources/JsonSchema/submitAnswersSchema.json
  src/test/resources/JsonTestFiles/DobSubmitAnswer.json
  src/test/resources/JsonTestFiles/FirstSubmitAnswer.json
  src/test/resources/JsonTestFiles/InvalidJson1.json
  src/test/resources/JsonTestFiles/InvalidVersion.json
Labels: ns:pcq, rel:pcq-backend-pr-43
