Repository hmcts/pcq-backend, pull requests merged in 2021-07, with the labels that each got.

#351 Nightly dev
  security.sh
Labels: ns:pcq, prd:pcq, rel:pcq-backend-pr-351

#367 PCQ-885: UpdatedPcqCommonsLocation
  build.gradle
Labels: ns:pcq, prd:pcq, rel:pcq-backend-pr-367

#369 fix for CVE-2021-33037
  build.gradle
Labels: ns:pcq, prd:pcq, rel:pcq-backend-pr-369

#372 PCQ-880: Updated to add fortify pipeline
  Jenkinsfile_nightly
  build.gradle
  config/fortify-client.properties
Labels: ns:pcq, prd:pcq, rel:pcq-backend-pr-372
