Repository hmcts/pcq-backend, pull requests merged in 2021-12, with the labels that each got.

#390 PCQ-1113 High level documentation to API and end-points tagging
  build.gradle
  src/main/java/uk/gov/hmcts/reform/pcqbackend/config/SwaggerConfiguration.java
  src/main/java/uk/gov/hmcts/reform/pcqbackend/controllers/ConsolidationController.java
  src/main/java/uk/gov/hmcts/reform/pcqbackend/controllers/PcqAnswersController.java
  src/main/java/uk/gov/hmcts/reform/pcqbackend/controllers/SasTokenController.java
Labels: ns:pcq, prd:pcq, rel:pcq-backend-pr-390

#393 PCQ-1190 Disable Fortify Scan for backend
  Jenkinsfile_nightly
Labels: ns:pcq, prd:pcq, rel:pcq-backend-pr-393

#394 PCQ-1195 log4j upgrade
  build.gradle
Labels: ns:pcq, prd:pcq, rel:pcq-backend-pr-394

#396 PCQ-1212 Enable Fortify scan
  Jenkinsfile_nightly
Labels: ns:pcq, prd:pcq, rel:pcq-backend-pr-396

#395 PCQ‐1134: Update pcq-backend to Gradle 7.2
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
Labels: ns:pcq, prd:pcq, rel:pcq-backend-pr-395

#397 Revert "PCQ‐1134: Update pcq-backend to Gradle 7.2"
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
Labels: ns:pcq, prd:pcq, rel:pcq-backend-pr-397
