Repository hmcts/pcq-backend, pull requests merged in 2022-05, with the labels that each got.

#419 PCQ-1421-remove-redundant-vulnerability-suppressions
  config/owasp/suppressions.xml
Labels: ns:pcq, prd:pcq, rel:pcq-backend-pr-419

#421 PCQ-1333 Spring Framework Update
  build.gradle
  config/pmd/ruleset.xml
  src/integrationTest/resources/application.properties
  src/main/java/uk/gov/hmcts/reform/pcqbackend/config/SwaggerConfiguration.java
  src/main/resources/application.properties
Labels: ns:pcq, prd:pcq, rel:pcq-backend-pr-421

#422 PCQ-1333 Other upgrade
  build.gradle
Labels: ns:pcq, prd:pcq, rel:pcq-backend-pr-422

#423 PCQ-1373-Dependency-check-netty-CVE-2022-24823
  build.gradle
Labels: ns:pcq, prd:pcq, rel:pcq-backend-pr-423

#426 PCQ-699 depedency check fix
  build.gradle
Labels: ns:pcq, prd:pcq, rel:pcq-backend-pr-426
