Repository hmcts/pcq-backend, pull requests merged in 2022-02, with the labels that each got.

#401 PCQ-1236 hmcts library update
  build.gradle
Labels: ns:pcq, prd:pcq, rel:pcq-backend-pr-401

#403 Pcq 1338 dependency check
  build.gradle
Labels: ns:pcq, prd:pcq, rel:pcq-backend-pr-403

#404 PCQ-986: Spring Security dependency check fix
  build.gradle
Labels: ns:pcq, prd:pcq, rel:pcq-backend-pr-404

#406 Update Jenkinsfile_nightly
  Jenkinsfile_nightly
Labels: ns:pcq, prd:pcq, rel:pcq-backend-pr-406
