Repository hmcts/pcq-backend, pull requests merged in 2022-12, with the labels that each got.

#535 PCQ-1606 Upgrade Terraform version
  infrastructure/.terraform-version
Labels: ns:pcq, prd:pcq, keep-helm, rel:pcq-backend-pr-535

#538 Remove deployment_namespace
  infrastructure/variables.tf
Labels: ns:pcq, prd:pcq, rel:pcq-backend-pr-538

#542 PCQ-1617 changing dependabot configuration
  .github/dependabot.yml
Labels: ns:pcq, prd:pcq, rel:pcq-backend-pr-542

#546 PCQ-1620 dependency fix
  config/owasp/suppressions.xml
Labels: ns:pcq, prd:pcq, rel:pcq-backend-pr-546
