Repository hmcts/pcq-backend, pull requests merged in 2022-11, with the labels that each got.

#509 PCQ-1596 dependency cheeck fix
  build.gradle
Labels: ns:pcq, prd:pcq, rel:pcq-backend-pr-509

#512 PCQ-1593 Add Sonar Badges and Overview
  README.md
Labels: ns:pcq, prd:pcq, rel:pcq-backend-pr-512

#513 PCQ-1595 Cleanup helm release on success
  .github/PULL_REQUEST_TEMPLATE.md
  Jenkinsfile_CNP
Labels: ns:pcq, prd:pcq, rel:pcq-backend-pr-513

#515 PCQ-1600 Library upgrade
  build.gradle
Labels: ns:pcq, prd:pcq, rel:pcq-backend-pr-515

#518 PCQ-1600 libraries upgrade
  build.gradle
  charts/pcq-backend/Chart.yaml
Labels: ns:pcq, prd:pcq, rel:pcq-backend-pr-518

#519 PCQ-1600 libraries upgrade
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
Labels: ns:pcq, prd:pcq, rel:pcq-backend-pr-519

#520 PCQ-1600 Upgarding libraries
  build.gradle
Labels: ns:pcq, prd:pcq, rel:pcq-backend-pr-520

#534 PCQ-1613: Update postgresql library.
  build.gradle
Labels: ns:pcq, prd:pcq, rel:pcq-backend-pr-534
