Repository hmcts/pcq-backend, pull requests merged in 2022-04, with the labels that each got.

#412 PCQ-962 Upgrade libraries
  build.gradle
Labels: ns:pcq, prd:pcq, rel:pcq-backend-pr-412

#413 PCQ-1099 code smell fix
  src/functionalTest/java/uk/gov/hmcts/reform/pcqbackend/client/PcqBackEndServiceClient.java
  src/functionalTest/java/uk/gov/hmcts/reform/pcqbackend/controllers/PcqWithoutCaseTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/pcqbackend/controllers/GetPcqRecordWithoutCaseTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/pcqbackend/controllers/GetPcqWithoutCaseTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/pcqbackend/util/PcqBackEndClient.java
  src/main/java/uk/gov/hmcts/reform/pcqbackend/config/TransformerColumnKeyLoader.java
  src/main/java/uk/gov/hmcts/reform/pcqbackend/controllers/ConsolidationController.java
  src/test/java/uk/gov/hmcts/reform/pcqbackend/controllers/ConsolidationControllerTest.java
Labels: ns:pcq, prd:pcq, rel:pcq-backend-pr-413

#414 PCQ-966-dependency-check-spring-beans
  build.gradle
Labels: ns:pcq, prd:pcq, rel:pcq-backend-pr-414

#415 PCQ-1452: Suppress vulnerability with spring-plugin.
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:pcq, prd:pcq, rel:pcq-backend-pr-415

#416 PCQ-1424-Dependency-check-spring-plugin
  config/owasp/suppressions.xml
Labels: ns:pcq, prd:pcq, rel:pcq-backend-pr-416

#417 PCQ-1423-dependency-check-spring-5.3.18
  build.gradle
Labels: ns:pcq, prd:pcq, rel:pcq-backend-pr-417

#418 PCQ-968 Security scan fix
  security.sh
Labels: ns:pcq, prd:pcq, rel:pcq-backend-pr-418
