Repository hmcts/pcq-backend, pull requests merged in 2023-11, with the labels that each got.

#810 PCQ-1842 remove dependabot config
  .github/dependabot.yml
Labels: prd:pcq, ns:pcq, rel:pcq-backend-pr-810

#813 PCQ-1750 Log 1% of health message
  lib/applicationinsights.json
Labels: prd:pcq, ns:pcq, rel:pcq-backend-pr-813

#830 Add read only user permissions
  config/owasp/suppressions.xml
  infrastructure/main.tf
Labels: prd:pcq, ns:pcq, destroy, rel:pcq-backend-pr-830

#837 Add sdp read only user
  infrastructure/sdp.tf
Labels: prd:pcq, ns:pcq, add-or-update, rel:pcq-backend-pr-837
