Repository hmcts/pcq-backend, pull requests merged in 2023-08, with the labels that each got.

#664 PCQ-1783 address CVE-2023-34035
  build.gradle
  src/main/java/uk/gov/hmcts/reform/pcqbackend/security/SecurityConfiguration.java
Labels: ns:pcq, prd:pcq, rel:pcq-backend-pr-664

#666 PCQ-1782 changing config to 120 days
  src/functionalTest/java/uk/gov/hmcts/reform/pcqbackend/controllers/PcqRecordWithoutCaseTest.java
  src/functionalTest/resources/application-functional.yaml
  src/main/resources/application.yaml
Labels: prd:pcq, ns:pcq, rel:pcq-backend-pr-666

#668 PCQ-1782 changing config to 150 days
  src/functionalTest/java/uk/gov/hmcts/reform/pcqbackend/controllers/PcqRecordWithoutCaseTest.java
  src/functionalTest/resources/application-functional.yaml
  src/main/resources/application.yaml
Labels: prd:pcq, ns:pcq, rel:pcq-backend-pr-668

#669 PCQ-1782 changing config to 180 days
  src/functionalTest/java/uk/gov/hmcts/reform/pcqbackend/controllers/PcqRecordWithoutCaseTest.java
  src/functionalTest/resources/application-functional.yaml
  src/main/resources/application.yaml
Labels: prd:pcq, ns:pcq, rel:pcq-backend-pr-669

#670 PCQ-1782 changing config to 210
  src/functionalTest/java/uk/gov/hmcts/reform/pcqbackend/controllers/PcqBaseFunctionalTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/pcqbackend/controllers/PcqRecordWithoutCaseTest.java
  src/functionalTest/resources/application-functional.yaml
  src/main/resources/application.yaml
Labels: prd:pcq, ns:pcq, rel:pcq-backend-pr-670

#673 PCQ-1782 changing config to 240 days
  src/functionalTest/resources/application-functional.yaml
  src/main/resources/application.yaml
Labels: prd:pcq, ns:pcq, rel:pcq-backend-pr-673

#676 PCQ-1782 changing config to 270
  src/functionalTest/resources/application-functional.yaml
  src/main/resources/application.yaml
Labels: prd:pcq, ns:pcq, rel:pcq-backend-pr-676

#678 PCQ-1782 config to 300 days
  src/functionalTest/resources/application-functional.yaml
  src/main/resources/application.yaml
Labels: prd:pcq, ns:pcq, rel:pcq-backend-pr-678

#682 PCQ-1782 changing config to 330
  src/functionalTest/resources/application-functional.yaml
  src/main/resources/application.yaml
Labels: prd:pcq, ns:pcq, rel:pcq-backend-pr-682

#683 PCQ-1804 security scan fix
  audit.json
Labels: prd:pcq, ns:pcq, rel:pcq-backend-pr-683

#684 PCQ-1804 fix security scan
  audit.json
Labels: prd:pcq, ns:pcq, rel:pcq-backend-pr-684
