Repository hmcts/pcq-backend, pull requests merged in 2023-03, with the labels that each got.

#589 PCQ-1648 configuring dependabot for particular day
  .github/dependabot.yml
  build.gradle
Labels: ns:pcq, prd:pcq, rel:pcq-backend-pr-589

#590 PCQ-1623 fixing Suppression CVE-2021-37533
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:pcq, prd:pcq, rel:pcq-backend-pr-590

#596 PCQ-1659 suppress CVE-2022-1471
  config/owasp/suppressions.xml
Labels: ns:pcq, prd:pcq, rel:pcq-backend-pr-596

#602 Fix CVE-2023-28708
  build.gradle
Labels: ns:pcq, prd:pcq, rel:pcq-backend-pr-602

#603 Spring framework cve-2023-20861 fix
  build.gradle
Labels: ns:pcq, prd:pcq, rel:pcq-backend-pr-603
