Repository hmcts/pcq-backend, pull requests merged in 2024-05, with the labels that each got.

#1025 PCQ-1901 Make number_of_days_limit configurable
  src/functionalTest/resources/application-functional.yaml
  src/integrationTest/resources/application.yaml
  src/main/resources/application.yaml
Labels: prd:pcq, ns:pcq, aat/no-changes, prod/no-changes, rel:pcq-backend-pr-1025

#1024 LAU-880 submitAnswers API inserts last updated timestamp
  src/main/java/uk/gov/hmcts/reform/pcqbackend/domain/ProtectedCharacteristics.java
  src/main/java/uk/gov/hmcts/reform/pcqbackend/repository/ProtectedCharacteristicsRepository.java
  src/main/java/uk/gov/hmcts/reform/pcqbackend/repository/impl/ProtectedCharacteristicsRepositoryImpl.java
  src/main/java/uk/gov/hmcts/reform/pcqbackend/service/SubmitAnswersService.java
Labels: prd:pcq, ns:pcq, rel:pcq-backend-pr-1024

#1040 LAU-841 enable security scan once a month only
  Jenkinsfile_nightly
Labels: prd:pcq, ns:pcq, rel:pcq-backend-pr-1040
